// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_history.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginHistory = `-- name: CreateLoginHistory :one
INSERT INTO login_history (
    user_id, oauth_provider, ip_address, user_agent, success, failure_reason
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, oauth_provider, ip_address, user_agent, success, failure_reason, created_at
`

type CreateLoginHistoryParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	OauthProvider pgtype.Text `json:"oauth_provider"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	Success       bool        `json:"success"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) (LoginHistory, error) {
	row := q.db.QueryRow(ctx, createLoginHistory,
		arg.UserID,
		arg.OauthProvider,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.FailureReason,
	)
	var i LoginHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OauthProvider,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginHistory = `-- name: GetLoginHistory :many
SELECT id, user_id, oauth_provider, ip_address, user_agent, success, failure_reason, created_at FROM login_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) GetLoginHistory(ctx context.Context, userID uuid.UUID) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, getLoginHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginHistory{}
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OauthProvider,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
