// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthProvider = `-- name: CreateOAuthProvider :one
INSERT INTO oauth_providers (user_id, provider, provider_id, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_id, email, created_at, updated_at
`

type CreateOAuthProviderParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	Email      pgtype.Text `json:"email"`
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, createOAuthProvider,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
	)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthProvider = `-- name: GetOAuthProvider :one
SELECT id, user_id, provider, provider_id, email, created_at, updated_at FROM oauth_providers
WHERE provider = $1 AND provider_id = $2
`

type GetOAuthProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthProvider(ctx context.Context, arg GetOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProvider, arg.Provider, arg.ProviderID)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
