// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) (LoginHistory, error)
	CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) (OauthProvider, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveSessionFamilies(ctx context.Context, userID uuid.UUID) ([]GetActiveSessionFamiliesRow, error)
	GetActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	GetLoginHistory(ctx context.Context, userID uuid.UUID) ([]LoginHistory, error)
	GetOAuthProvider(ctx context.Context, arg GetOAuthProviderParams) (OauthProvider, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	GrantRole(ctx context.Context, arg GrantRoleParams) error
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateTokenUsedAt(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
