// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token_hash, family_id, parent_id,
    ip_address, user_agent, device_name, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, token_hash, family_id, parent_id, ip_address, user_agent, device_name, expires_at, created_at, used_at, revoked_at, revoked_reason
`

type CreateRefreshTokenParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	FamilyID   uuid.UUID          `json:"family_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	DeviceName pgtype.Text        `json:"device_name"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ParentID,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getActiveSessionFamilies = `-- name: GetActiveSessionFamilies :many
SELECT DISTINCT ON (family_id)
    id, user_id, family_id, ip_address, user_agent, device_name,
    created_at, used_at, expires_at
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY family_id, created_at DESC
LIMIT 20
`

type GetActiveSessionFamiliesRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	FamilyID   uuid.UUID          `json:"family_id"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	DeviceName pgtype.Text        `json:"device_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveSessionFamilies(ctx context.Context, userID uuid.UUID) ([]GetActiveSessionFamiliesRow, error) {
	rows, err := q.db.Query(ctx, getActiveSessionFamilies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveSessionFamiliesRow{}
	for rows.Next() {
		var i GetActiveSessionFamiliesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceName,
			&i.CreatedAt,
			&i.UsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSessionsByUserID = `-- name: GetActiveSessionsByUserID :many
SELECT id, user_id, token_hash, family_id, parent_id, ip_address, user_agent, device_name, expires_at, created_at, used_at, revoked_at, revoked_reason FROM refresh_tokens
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) GetActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.FamilyID,
			&i.ParentID,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceName,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, parent_id, ip_address, user_agent, device_name, expires_at, created_at, used_at, revoked_at, revoked_reason FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), revoked_reason = 'logout_all'
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), revoked_reason = $2
WHERE id = $1
`

type RevokeRefreshTokenParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokedReason)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), revoked_reason = 'family_compromised'
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, familyID)
	return err
}

const updateTokenUsedAt = `-- name: UpdateTokenUsedAt :exec
UPDATE refresh_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateTokenUsedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenUsedAt, id)
	return err
}
